# Generated by Django 4.2.15 on 2024-11-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userpreference_delete_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="genres",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="moods",
            field=models.JSONField(default=list),
        ),
    ]
